apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website-app
  labels:
    app: my-website-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-website-app
  template:
    metadata:
      labels:
        app: my-website-app
    spec:
      containers:
      - name: web
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: my-website-app-service
spec:
  selector:
    app: my-website-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
