apiVersion: v1
kind: Service
metadata:
  name: mcp-service
  annotations:
    # For EKS LoadBalancer
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"
spec:
  type: LoadBalancer  # Use LoadBalancer for EKS, will be NodePort for Minikube
  selector:
    app: mcp-server
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None

---

# Alternative NodePort service for Minikube
apiVersion: v1
kind: Service
metadata:
  name: mcp-service-nodeport
  annotations:
    description: "NodePort service for Minikube environments"
spec:
  type: NodePort
  selector:
    app: mcp-server
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30173
    protocol: TCP
